#puerto donde escucha el broker mqtt
listener 1883
#desactiva las conexiones anonimas
allow_anonymous false
#archivo donde se almacenan los usuarios y contrasenas
password_file /mosquitto/config/passwords
#activa la persistencia de mensajes
persistence true
#directorio donde mosquitto almacena los datos persistentes
persistence_location /mosquitto/data/
#envia los logs a la salida del contenedor
log_dest stdout
#registra errores
log_type error
#registra advertencias
log_type warning
#registra informacion general
log_type notice
#registra informacion util durante desarrollo
log_type information
# que pueden permanecer pendientes de confirmacion
max_inflight_messages 200