{
 "title": "Logs App",
 "tags": [
  "smartbancs",
  "logs",
  "loki",
  "provisionado"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "filtro_nombre", "label": "Filtro nombre", "query": "label_values(service)" },
   { "name": "buscar", "label": "Buscar valor" }
  ]
 },
 "panels": [
  { "title": "Logs App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logs ultimos 5m",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({service=~\"$filtro_nombre\"} |= \"$buscar\" [5m]))",
     "legendFormat": "logs"
    }
   ]
  },
  {
   "title": "Errores ultimos 5m",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({service=~\"$filtro_nombre\"} |= \"$buscar\" |~ \"(?i)(error|exception|traceback|failed|fallo)\" [5m]))",
     "legendFormat": "errores"
    }
   ]
  },
  {
   "title": "Flujo de aplicacion",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "{service=~\"$filtro_nombre\"} |= \"$buscar\""
    }
   ]
  },
  {
   "title": "Errores",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{service=~\"$filtro_nombre\"} |= \"$buscar\" |~ \"(?i)(error|exception|traceback|failed|fallo)\""
    }
   ]
  },
  {
   "title": "Eventos importantes",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{service=~\"$filtro_nombre\"} |= \"$buscar\" |~ \"(?i)(Worker|Lote PostgreSQL|Redis Stream|MQTT|PostgreSQL|DLQ|transferencia|transaccion|persistencia|publicador|recuperacion|conectado|iniciado|interrumpida|confirmado|procesado|recomendacion|IA|ia|error|warning)\""
    }
   ]
  }
 ]
}